### ISSUE TITLE
CM12.1 Progress

### ISSUE THREAD

**Issue by Caio99BR** [TeamVee/android_device_lge_vee3#7]
# Working
- [x] WiFi (And Thetering)
- [x] Bluetooth (And Thetering)
- [x] USB (And Thetering)
- [x] Internal and External Storage
- [x] LED
- [x] GPS
- [x] Sensors (All)
- [x] Audio (Fully Working)
- [x] Video Playback
- [x] Model Setting (Via Init)
- [x] Camera (Camcoder WorkArounded)
# Not Working
- [ ] RIL (Single and Dual)

**Comment by Caio99BR** [comment]
External Storage fixed on commit https://github.com/TeamVee/android_device_lge_vee3/commit/72e8a35c6de079d154f1a4bdf036a571a5d975f0

**Comment by Caio99BR** [comment]
Sound fixed in related commits: https://github.com/TeamVee/android_device_lge_vee-common/commit/82fcb0a878774fb3d4e6d3e7bfc33bf91b7d1389 https://github.com/TeamVee/android_device_lge_vee-common/commit/73817001f26d562f908118456826d4e708d39d2e https://github.com/TeamVee/android_device_lge_vee-common/commit/6f7ba9123dbd551f97b3f9b9b5ea39474523a384

---

Bluetooth fixed in commit: https://github.com/TeamVee/android_device_lge_vee-common/commit/6f7ba9123dbd551f97b3f9b9b5ea39474523a384

---

Sensors fixed in commit : https://github.com/TeamVee/android_device_lge_vee-common/commit/6f7ba9123dbd551f97b3f9b9b5ea39474523a384

---

Boot/Video Playback fixed in related commits: https://github.com/TeamVee/android_device_lge_vee-common/commit/8a3964098db971e0eafb879dd75ff9f9f6027e46 https://github.com/TeamVee/android_device_lge_vee-common/commit/d32ced7e96432349a81cd48f85a32f8785f53629 https://github.com/TeamVee/android_device_lge_vee-common/commit/6f7ba9123dbd551f97b3f9b9b5ea39474523a384

---

SEPolicy Denials fixed in related commits: https://github.com/TeamVee/android_device_lge_vee-common/commit/3641e0624853ae81ef9a880aaf9c449e05545eba https://github.com/TeamVee/android_device_lge_vee-common/commit/2b669e4421f8fb3c067304472bf4266818e89916 https://github.com/TeamVee/android_device_lge_vee-common/commit/b3f13d92a2ade3dde0c4ee42d272eae9cb5a48a6

**Comment by Caio99BR** [comment]
Audio in EarPhone fixed in related commits: https://github.com/TeamVee/android_device_lge_vee-common/commit/398e2cbc378f0f4d2071b9b469fdff38e95b456c https://github.com/TeamVee/android_device_lge_vee-common/commit/95e25f4dae86ca6ea01972cd3f7eb45ec276f15a https://github.com/TeamVee/android_device_lge_vee-common/commit/9e5d3df8a33f3fd2bb5bb1f72835f6267e70655e https://github.com/TeamVee/android_device_lge_vee-common/commit/9bcac012d26b8c0115069ad5311874e340561069 https://github.com/TeamVee/android_device_lge_vee-common/commit/c2b59568d1c86c2cb7bf5deba18f7178f6f585f1 https://github.com/TeamVee/android_device_lge_vee-common/commit/72fa76932fd675ce9db05bf27aabe6648d844c44 https://github.com/TeamVee/android_device_lge_vee-common/commit/ec6dc9de0e224cedf2687947cc25d05e8e5b9fe7 https://github.com/TeamVee/android_device_lge_vee-common/commit/35580d790ad16e89b15beb142ca7c9a6e8d714bf https://github.com/TeamVee/android_device_lge_vee-common/commit/24908bdb09405088d8726a9d117979c335134262 https://github.com/TeamVee/android_device_lge_vee-common/commit/38e209127d1382d1b4f08dd1fcea160b5ee9df6f https://github.com/TeamVee/android_device_lge_vee-common/commit/949704300095974f374bad89f59a8b8c8100eda1

**Comment by Caio99BR** [comment]
Audio Recording fixed in related commits: https://github.com/TeamVee/android_device_lge_vee-common/commit/49ac86961d51588a6e4a91293754398a47e1be13 https://github.com/TeamVee/android_device_lge_vee-common/commit/26eb96e6711feb7c318f741359f614d83a71050d https://github.com/TeamVee/android_device_lge_vee-common/commit/9ee59dd1282596c0a8f2a081b80e9e79989789c2

**Comment by Caio99BR** [comment]
Model Setting fixed in related commits: https://github.com/TeamVee/android_device_lge_vee3/commit/e3aa4281b50173ea4df5cec2032914866fddc5cb https://github.com/TeamVee/android_device_lge_v1/commit/1bc5bfe02c3acc8c2c2f2487190d321635b1d650 https://github.com/TeamVee/android_device_lge_vee-common/commit/d72d0a0d78576db54f8c2b9eea1a81d689e11297 https://github.com/TeamVee/android_device_lge_vee-common/commit/8e8d9d8da2a21033d1d966069f38dfc590e392fd

**Comment by Caio99BR** [comment]
BT Address fixed in commit: https://github.com/TeamVee/android_device_lge_vee-common/commit/dd65993bb9ff09d2f719011a36c0e33738bb2bc7

**Comment by meytrik** [comment]
good work and i´m hoping

**Comment by Caio99BR** [comment]
Camera fixed in related commits: https://github.com/TeamVee/android_.repo_local_manifests/commit/ff6a931423f8012ec072cc9b71251e85d1ad3678 https://github.com/TeamVee/android_vendor_lge/commit/eac23f9d7bc75f40cb8d079c3646cff0deeae656

**Comment by Caio99BR** [comment]
Gapps possible fix in commit: https://github.com/TeamVee/android_device_lge_vee-common/commit/113cbac71b7a25bf16031e700a9167aec333c9fa

**Comment by Caio99BR** [comment]
[Possible/Test] RIL partially fixed in related commits: https://github.com/TeamVee/android_device_lge_vee-common/commit/b76f4c8f93e8129b29c4f3e73d5dddd38dc1f341 https://github.com/TeamVee/android_device_lge_vee-common/commit/e41ec3bd3688329358f14cfa6535977094d9c5a6

**Comment by Caio99BR** [comment]
RIL need a new builded from source.
For Camcoder no fix.

I am not fully working on this, issue closed for now.

**Comment by msfjarvis** [comment]
@Caio99BR No chance of fixing the camcorder? I was kinda hoping you manage to fix it and I cherry-pick it into HTCLegacy/android_device_htc_pico to fix Camcorder.

**Comment by Caio99BR** [comment]
Idk how to fix, im waiting @neutrondev03 try to fix it

**Comment by msfjarvis** [comment]
@Caio99BR Thanks for replying. I'll keep an eye here to check on the status

**Comment by Caio99BR** [comment]
Init fixed in merge: https://github.com/TeamVee/android_device_lge_vee-common/pull/20

**Comment by Caio99BR** [comment]
Hey @MSF-Jarvis you can workaround camcoder with this: https://github.com/TeamVee/android_device_lge_vee3/commit/6ef2f352f3782ea944aeb0779876852ffebc288b

**Comment by Caio99BR** [comment]
Media Player workarounded in commit: https://github.com/TeamVee/android_device_lge_vee3/commit/f24b7c15945d4ccb17fcc2f66ca37453a88541d3

---

Camcoder workarounded in commit: https://github.com/TeamVee/android_device_lge_vee3/commit/6ef2f352f3782ea944aeb0779876852ffebc288b

**Comment by Caio99BR** [comment]
Video lags fixed in commit: https://github.com/TeamVee/android_device_lge_vee3/commit/977f085d95a2f455f2436aa7ad751ba9c0007344
